#!/usr/bin/env bash
# Updating package lists and install Nginx
sudo apt update
sudo apt install -y nginx

# Sets the Nginx configuration file path
nginx_conf="/etc/nginx/sites-available/default"

# Adds custom HTTP response header to Nginx configuration
echo "server {" | sudo tee -a $nginx_conf
echo "    listen 80 default_server;" | sudo tee -a $nginx_conf
echo "    server_name _;" | sudo tee -a $nginx_conf
echo "    add_header X-Served-By \$hostname;" | sudo tee -a $nginx_conf
echo "    # Additional Nginx configuration..." | sudo tee -a $nginx_conf
echo "}" | sudo tee -a $nginx_conf

sudo systemctl restart nginx