#!/usr/bin/env bash
# Installing and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 238551-web-01 54.158.222.196:80 check
   server 238551-web-02 34.207.120.67:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start