#!/usr/bin/env bash

for pid in $pids; do
    # Read the command associated with the process from /proc/<pid>/cmdline
    cmd=$(tr '\0' ' ' < "$pid"/cmdline)
    # Get only the process name (excluding path and arguments)
    process_name=$(basename "$cmd")
    
    # Check if the process name contains the word "bash"
    if [[ "$process_name" == *"bash"* ]]; then
        echo "$pid    $process_name"
    fi
done
