#!/usr/bin/env bash
# Configuring an Ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i 's/^127.0.0.1\tlocalhost$/127.0.0.2\tlocalhost/' /etc/hosts
sudo echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts