#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user, listens on port 8080, and restarts the service.

# Setting the nginx user in the Nginx configuration
sed -i 's/user\s*[^;]*;/user nginx;/g' /etc/nginx/nginx.conf

# Sets Nginx to listen on all active IPs on port 8080
sed -i 's/listen\s*[^;]*;/listen 8080 default_server;/g' /etc/nginx/sites-available/default

# Restarting Nginx to apply the changes
service nginx restart

echo "Nginx has been configured to run as the nginx user and listen on port 8080."
