#!/usr/bin/env bash
# Connects to server with key in ~/.ssh/school

# Set correct permissions and ownership for the key
chmod 600 ~/.ssh/school
chown $USER:$USER ~/.ssh/school
ssh-copy-id -i ~/.ssh/school.pub ubuntu@54.158.222.196

eval "$(ssh-agent -s)"
ssh-add ~/.ssh/school

# Connects to the server with verbose output
ssh -vvv -i ~/.ssh/school ubuntu@54.158.222.196
